# HiFi use case configuration for xiaomi cepheus.
# Author: XiaoYeZi <qaz6750@outlook.com>
#
# Playback Devices
#  - Internal Speaker    : CS35L41 Amp driver : MultiMedia1 <-> QUAT_MI2S_RX
#
# Capture Devices
#  - Internal Microphone : WCD9340 ADC1       : MultiMedia1 <-> SLIMBUS_5_TX

SectionVerb {
	Value {
		TQ "HiFi"
	}
}

SectionDevice."Speaker" {
	Comment "Internal Speaker"

	EnableSequence [
		cset "name='QUAT_MI2S_RX Audio Mixer MultiMedia1' 1"
	]

	DisableSequence [
		cset "name='QUAT_MI2S_RX Audio Mixer MultiMedia1' 0"
	]

	Value {
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId},0" # MultiMedia1
		PlaybackChannels 1
	}
}

SectionDevice."InternalMic" {
	Comment "Internal Microphone"

	EnableSequence [
		cset "name='AMIC MUX0' 'ADC1'"
		cset "name='ADC MUX0' 'AMIC'"
		cset "name='CDC_IF TX0 MUX' 'DEC0'"
		cset "name='AIF1_CAP Mixer SLIM TX0' 1"
		cset "name='SLIMBUS_5_TX Audio Mixer MultiMedia1' 1"
	]

	DisableSequence [
		cset "name='SLIMBUS_5_TX Audio Mixer MultiMedia1' 0"
		cset "name='AIF1_CAP Mixer SLIM TX0' 0"
	]

	Value {
		CapturePriority 200
		CapturePCM "hw:${CardId},0"
		CaptureChannels 1
	}
}
